<script setup>
import { Head } from '@inertiajs/vue3';
import { PhTextbox } from '@phosphor-icons/vue';

const props = defineProps({
    form: Object,
    settings: Object
});
</script>

<template>
    <Head :title="`Preview: ${form.title}`" />
    
    <div class="min-h-screen bg-base-300 flex items-center justify-center p-4">
        <div class="max-w-xl w-full bg-base-100 rounded-3xl shadow-2xl overflow-hidden border border-white/5">
            <!-- Header -->
            <div class="bg-primary p-8 text-primary-content relative overflow-hidden">
                <div class="relative z-10 flex items-center gap-4">
                    <div class="w-12 h-12 bg-white/20 rounded-2xl flex items-center justify-center backdrop-blur-sm">
                        <PhTextbox weight="bold" class="w-6 h-6" />
                    </div>
                    <div>
                        <h1 class="text-2xl font-black uppercase tracking-tight">{{ form.title }}</h1>
                        <p class="text-xs opacity-70 font-medium">Public Preview Mode</p>
                    </div>
                </div>
                <!-- Abstract background shapes -->
                <div class="absolute -right-4 -top-4 w-32 h-32 bg-white/10 rounded-full blur-3xl"></div>
                <div class="absolute -left-10 -bottom-10 w-48 h-48 bg-black/10 rounded-full blur-3xl"></div>
            </div>

            <!-- Form Body -->
            <div class="p-8">
                <div v-if="form.content && form.content.length" class="space-y-6">
                    <div v-for="(field, index) in form.content" :key="index" class="form-control w-full">
                        <label class="label">
                            <span class="label-text font-bold text-xs uppercase tracking-wider opacity-60">{{ field.label }}</span>
                            <span v-if="field.required" class="label-text-alt text-error">* Required</span>
                        </label>
                        
                        <input v-if="field.type === 'text' || field.type === 'email' || field.type === 'tel'" 
                               :type="field.type" 
                               :placeholder="field.placeholder" 
                               class="input input-bordered w-full bg-base-200/50 focus:border-primary transition-all rounded-xl" />
                        
                        <textarea v-else-if="field.type === 'textarea'" 
                                  :placeholder="field.placeholder" 
                                  class="textarea textarea-bordered w-full h-32 bg-base-200/50 focus:border-primary transition-all rounded-xl"></textarea>
                        
                        <select v-else-if="field.type === 'select'" 
                                class="select select-bordered w-full bg-base-200/50 focus:border-primary transition-all rounded-xl">
                            <option disabled selected>{{ field.placeholder || 'Select an option' }}</option>
                            <option v-for="opt in field.options" :key="opt">{{ opt }}</option>
                        </select>
                    </div>

                    <div class="pt-4">
                        <button class="btn btn-primary btn-block rounded-xl h-14 font-black uppercase tracking-widest text-xs">
                            {{ form.settings?.submit_label || 'Submit Message' }}
                        </button>
                    </div>
                </div>
                <div v-else class="text-center py-12 opacity-40">
                    <p class="text-sm italic">This form has no fields yet.</p>
                </div>
            </div>

            <!-- Footer -->
            <div class="bg-base-200/50 p-4 text-center border-t border-white/5">
                <p class="text-[10px] uppercase tracking-widest opacity-30 font-bold">Generated by Antigravity CMS</p>
            </div>
        </div>
    </div>
</template>
